### ISSUE TITLE
deduplicate_images.py 报错

### ISSUE THREAD

**Issue by aigias** [WSH032/image-deduplicate-cluster-webui#1]
作者好，

正常安装后，运行run_deduplicate_images.ps1时报错：

File "E:\AI SCRIPTS\image-deduplicate-cluster-webui\deduplicate_images.py", line 417, in <module>
    delet_button.click(fn=delet,
  File "E:\AI SCRIPTS\image-deduplicate-cluster-webui\venv\lib\site-packages\gradio\events.py", line 132, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
  File "E:\AI SCRIPTS\image-deduplicate-cluster-webui\venv\lib\site-packages\gradio\blocks.py", line 237, in set_event_trigger
    special_args(fn) if fn else (None, None, None)
  File "E:\AI SCRIPTS\image-deduplicate-cluster-webui\venv\lib\site-packages\gradio\helpers.py", line 631, in special_args
    elif type_hint and issubclass(type_hint, EventData):
TypeError: issubclass() arg 1 must be a class

麻烦看看，感谢。

**Comment by WSH032** [comment]
收到，能告诉我是怎么触发这个错误的吗？
是在按下删除按钮的时候吗？
python版本大于3.9吗？gradio版本是多少呢？

**Comment by WSH032** [comment]
这似乎是gradio的问题https://github.com/gradio-app/gradio/issues/3514

`File "E:\AI SCRIPTS\image-deduplicate-cluster-webui\deduplicate_images.py", line 417, in
delet_button.click(fn=delet,`

这一行报错显示错误可能与这段代码有关https://github.com/WSH032/image-deduplicate-cluster-webui/blob/8e4b73c0626c43edbc5c2402b31749839b133264/deduplicate_images.py#L199

---

deduplicate_images.py在`python==3.9, gradio==3.29.0` 和 `python==3.10, gradio==3.32.0` 上都做过测试

不清楚你的python版本和gradio版本，我无法复现这个问题

结合 https://github.com/gradio-app/gradio/issues/3514 中提到的信息，有可能是类型注解的问题

你能像修改TXT文本那样，打开`deduplicate_images.py`，将其中第199行进行以下修改，观察问题是否消失吗？

```diff
- def delet(duplicates_images_gallery: Tuple[str, str], delet_images_str: str): 
+ def delet(duplicates_images_gallery, delet_images_str): 
```

---

或者，尝试升级gradio版本

把`requirements.txt`中第二行做如下修改，然后再次运行`install.ps1`
```diff
- gradio>=3.28.0
+ gradio==3.32.0
```
---

感谢你的帮忙

**Comment by aigias** [comment]
Python版本3.10.8
1. 修改代码的方案尝试了，没能解决。错误提示变成另一种。
2. gradio原本是3.30，装了gradio 3.32，
Successfully uninstalled gradio-3.30.0
Successfully installed gradio-3.32.0
之后重新尝试，也没能解决，错误提示还是之前那几行

**Comment by aigias** [comment]
尝试了这个：https://github.com/gradio-app/gradio/issues/3514#issuecomment-1549918933
也无法解决 报错一样

**Comment by WSH032** [comment]
好的，感谢你的测试。
我稍后在colab上进一步实验看看。

**Comment by WSH032** [comment]
我实在复现不了这个报错，你可以用一下这个colab，看看有没有问题：

https://colab.research.google.com/drive/1hh2iK5lTcXA0XuuOCFXYs47lfcm-3Ksx?usp=sharing

无脑点击运行，注意**粗体字**的提示就行。

---

> 1. 修改代码的方案尝试了，没能解决。错误提示变成另一种。

新的报错是什么？

---

我晚点，或者明天发一个删掉全部类型注解的分支，到时候你clone新的分支看看能不能正常使用，venv虚拟环境就用之前那个就行。

顺便再次确认下，是查重WebUI其他功能都正常，确实能查出图片，**只是一按删除就报错吗？**

还是别的什么情况触发了这个报错？

**Comment by kuugaoggy** [comment]
- def delet(duplicates_images_gallery: Tuple[str, str], delet_images_str: str): 
+ def delet(duplicates_images_gallery, delet_images_str): 


- gradio>=3.28.0
+ gradio==3.32.0



试了这个方案，可以正常使用了

**Comment by WSH032** [comment]
所以我们基本确定是gradio的问题咯？
@aigias 像**kuugaoggy**上面提到的那样做仍然不能解决问题吗？
可以尝试上面那个colab，如果colab里也能正常运行，那基本可以肯定是环境的问题了。

---
我将在下次更新修改`requirement.txt`中`gradio>=3.31.0`，和目前的A1111 SD-WebUI环境一样

**Comment by aigias** [comment]
> 所以我们基本确定是gradio的问题咯？ @aigias 像**kuugaoggy**上面提到的那样做仍然不能解决问题吗？ 可以尝试上面那个colab，如果colab里也能正常运行，那基本可以肯定是环境的问题了。
> 
> 我将在下次更新修改`requirement.txt`中`gradio>=3.31.0`，和目前的A1111 SD-WebUI环境一样

一些反馈：
1）colab正常运行
2）重装gradio 3.31.0 + 代码修改：
- def delet(duplicates_images_gallery: Tuple[str, str], delet_images_str: str): 
+ def delet(duplicates_images_gallery, delet_images_str): 
——之后可正常运行
3）我分别尝试了gradio 3.30 ~ 3.32，在代码修改的基础上，均成功。**所以问题应该还是在修改代码那里**。我不确认之前为何在3.30版本修改代码后仍报错，至少今天同样情况已经不报错了。

另外我很想吐槽colab上你把image拼写为imges.....
运行时代码一直报错：该目录不存在。因我自己输入的目录是images，一度怀疑人生

**Comment by WSH032** [comment]
好的，**非常感谢**二位的帮助。:smile:

下一次更新我将注释掉类型注解。

---

> 另外我很想吐槽colab上你把image拼写为imges.....

我检查了一下，没有发现这个错误呀。如果确实存在的话，那么很抱歉因为我的疏忽浪费了你的时间。

---

如果没有进一步问题的话，我想可以关闭issue？
